name: "Boxt - NPM version and publish"
description: "Based upon a conventional changelog, versions and publishes a new NPM package to the registry"
branding:
  icon: box
  color: red
author: "Boxt"
inputs:
  author_email:
    description: "After the version is incremented - the user that makes the commit"
    required: false
    default: "conventional-changelog-npm-publish@noreply.github.com"
  author_name:
    description: "After the version is incremented - the user that makes the commit"
    required: false
    default: "conventional-changelog-npm-publish"
  commit_message:
    description: "Commit message - [VERSION_TYPE] is replaced with either patch, minor or major"
    required: false
    default: "Bumping [VERSION_TYPE] version"
runs:
  using: "node18"
  main: "dist/index.js"
